application: gym-data-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: request_handler.application
- url: /showGyms
  script: request_handler.application
- url: /crawlGyms
  script: request_handler.application
- url: /showCities
  script: request_handler.application
- url: /refreshCities
  script: request_handler.application
- url: /mineGymData
  script: request_handler.application

libraries:
- name: webapp2
  version: latest
